# -*- coding: utf-8 -*-
"""Sandeepak's Work on News fetch.ipynb

Automatically generated by Colaboratory.

Original file is located at     
    https://colab.research.google.com/drive/1xb4ASMw0umHMsD6GE5hjxHzoqGou-awC
"""

#pip install pygooglenews --upgrade

from pygooglenews import GoogleNews

gn = GoogleNews(country = 'IND')


def get_titles(search):
    stories = []
    search = gn.search(search)
    newsitem = search['entries']
    for item in newsitem:
        story = {
            'title': item.title,
            'link' : item.link
        }
        stories.append(story)
    return stories

print(get_titles('Fraud'))

gn = GoogleNews(country = 'IND')


def get_titles(search):
    stories = []
    search = gn.search(search)
    newsitem = search['entries']
    for item in newsitem:
        story = {
            'title': item.title,
            
        }
        stories.append(story)
    return stories

print(get_titles('Fraud'))

gn = GoogleNews(country = 'IND')


def get_titles(search):
    stories = []
    search = gn.search(search)
    newsitem = search['entries']
    for item in newsitem:
        story = {
            
            'link' : item.link
        }
        stories.append(story)
    return stories

print(get_titles('Fraud'))